# Generated by Django 3.1.7 on 2021-03-09 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar_card', models.ImageField(upload_to='adhar_cards')),
                ('USN', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('caste', models.CharField(choices=[('hindu', 'hindu'), ('muslim', 'muslim'), ('general', 'general'), ('sc', 'sc'), ('st', 'st')], max_length=50)),
                ('merit', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('processing', 'processing'), ('reject', 'reject'), ('approve', 'approve'), ('pending', 'pending')], default='pending', max_length=20)),
                ('college_id_card', models.ImageField(null=True, upload_to='id_cards')),
                ('certificate', models.ImageField(null=True, upload_to='certificates')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
