# Generated by Django 3.1.7 on 2021-03-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField()),
                ('income_ceiling', models.TextField()),
                ('value_of_scholarship', models.TextField()),
                ('how_and_when_to_apply', models.TextField()),
                ('publish', models.BooleanField(default=False)),
            ],
        ),
    ]
