# Generated by Django 3.1.7 on 2021-03-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
